### ISSUE TITLE
Support for table changing

### ISSUE THREAD

**Issue by ata2001** [itpp-labs/pos-addons#120]
Hi!
Could you please add support for this free and open source addon (the table changing one) in pos_multi_session_restaurant?

Links: https://www.odoo.com/apps/modules/9.0/pos_change_table/

https://github.com/CybroOdoo/CybroAddons/tree/9.0?files=1

**Comment by timboven** [comment]
+1

**Comment by yelizariev** [comment]
One can contact us to sponsor updates
it@it-projects.info

**Comment by alfieqashwa** [comment]
@yelizariev pos_change_table didn't synchronize when using pos_multi_session_restaurant module. Is there any update? 

thanks

**Comment by yelizariev** [comment]
It was made for 10.0 in #259.
One can try to backport updates to 9.0, integrate it with pos_change_table and send a Pull Request. Unfortunately, for such kind of updates our team is ready to provide service only for [app store buyers](https://www.odoo.com/apps/modules/9.0/pos_multi_session_restaurant), because it's not a bug and rather feature request
