### ISSUE TITLE
PoS Multi Session Restaurant

### ISSUE THREAD

**Issue by ljacobo** [itpp-labs/pos-addons#1258]
Hi,

There's a way to install this module without having to install those dependencies?

it have two modules as dependencies, and those modules have other dependencies as well, it is like a never ending loop.

thnks

**Comment by trojikman** [comment]
Hello,

The presence of a large number of dependencies is due to the technical complexity of the software product. From the point of view of software architecture and application debugging, this is the best solution. Part of the software is also used by other modules, and it would be foolish and not rational to repeat ourselves. 
And to be honest, for the first time I hear that someone is complaining about the presence of a large number of dependencies, especially if you take the module through the store, then there are no such problems.

Best regards
