### ISSUE TITLE
Problem with module pos_product_available and tg_pos_debt_notebook

### ISSUE THREAD

**Issue by straga** [itpp-labs/pos-addons#2]
Problem with module pos_product_available (In pos error with function get or ..).
Problem with module tg_pos_debt_notebook (In pos error with function push_order or ...)  It custom modules from Ivan Yelizariev.

I think it works on RC1 but in final release it modules don't works correctly. Js script errors.

**Comment by straga** [comment]
1. in tg_pos_notebook function not return pushed and if not order or empy show error "get_order".
2. in pos_product_available if not order or empy show error "get".

**Comment by yelizariev** [comment]
@straga These modules are published without any warranty. If you want to hire me to fix it, you can do it via odesk: https://www.odesk.com/users/~01d05f689c5d7ce2f3
I hope for your understanding

**Comment by straga** [comment]
How hours you need for fixit?

**Comment by yelizariev** [comment]
2-5 hours

**Comment by yelizariev** [comment]
@straga I am sorry, I was wrong about estimation of time to fixing. Actually it was easy to do, because you made quite detailed report. Thank you.

I made couple commits
https://github.com/yelizariev/pos-addons/commit/4e4baa7d1a76042f6c5529952802fb8765a14128
https://github.com/yelizariev/pos-addons/commit/bcd7ea707993f82348317709b4525b67c1d0038b
It should works now. 

If you are still interested in these modules, could you confirm that it works now.

**Comment by straga** [comment]
Need check, I am fixed it by self.

**Comment by yelizariev** [comment]
Ok, I've tested modules. At this moment I close the issue.
