### ISSUE TITLE
Quantity doesnt change on Poin of Sale

### ISSUE THREAD

**Issue by ferdjaoui** [itpp-labs/pos-addons#28]
The quantity of products in the Lot doesn't decrease when sold via Point of sale.

**Comment by yelizariev** [comment]
please specify what module do you mean

**Comment by ferdjaoui** [comment]
Module Product Lot

**Comment by yelizariev** [comment]
I need more details about the issue. What do you sell? Lot or Product? What quantity do you expect to descrease? Lot or Product?

**Comment by ferdjaoui** [comment]
Hi, when i sell a Lot the products quantity doesn't change, also when i sell products, the quantity on pack doesn't decrease regarding of available products. Regards.

**Comment by timboven** [comment]
Not sure if I can add it here or need to create a separate one but it matches with the subject of this ticket.
I've installed the available quantity module in a test-setup I'm currently using and the available stock is "not" updated. 

It is actually updated, but only after the table has paid its bill - but by that time, those units where not "available" anymore.
This could result in the state where a product is out of stock but still shows as available because the last unit of that product is still on a open table (so one that didn't pay yet).

Maybe this is a config mistake in my test setup or maybe something with this module - any directions to get this solved?
