### ISSUE TITLE
[10.0 - POS Multi-session] conflict during synchronization with 2 concurrent session

### ISSUE THREAD

**Issue by timboven** [itpp-labs/pos-addons#348]
We have a semi-reproducable issue - we used 2 sessions that worked on different tables and resulted in the error "conflict during synchronization" on at least on of the 2 sessions (and sometimes on both).
You can continue after the error - but you need to watch out as not all entered products are in the list anymore (so you need to check on what you need to re-add)

Testing strategy:
- Open session 1 on table A
- Open session 2 on table B
- in both sessions (at the same time) order a product Z 30 times by clicking it 30 times the product (to have the most chance on concurrency) - and somewhere during this you should get the error.

I tested this same scenario on both the 10.0 version and 9.0 - and it works perfectly on 9.0

**Comment by yelizariev** [comment]
At this moment, we do it by design. If you two session updates product quantity at the same time, then system checks that current session already knows latest version. The problem is that at this moment we update order as whole. E.g.


* POS1 sets: **product1=1 item;** 
* server saves: **product1=1 item;** 
* POS2 gets: **product1=1 item;** 

* POS1 adds new product: **product1=1 item; product2: 1 item;**
* server saves: **product1=1 item; product2: 1 item;**

Error scenario:
* POS2 still has: **product1=1 item**
* POS2 adds new product: **product1 = 1 item; product3 = 10 items;**
* server didn't accept updates from POS2, because otherwise we  lose product2

Success scenario:
* POS2  has updates from POS1: **product1=1 item; product2: 1 item;**
* POS2 adds new product: **product1=1 item; product2: 1 item;product3 = 10 items;**
* server  accept updates from POS2:  **product1=1 item; product2: 1 item;product3 = 10 items;**


============================
Solution here could be to send to server new version of updated lines and don't send new version of whole order (because other lines of order may be obsolete or be not synced yet). We postponed such development as consider such situations very rare (at your example you ask to click 30 times at the same product on both session -- almost imposible situation in real live). But we agree that it's better to fix it.

======================
Why it may works in 9.0.
My bet is that 9.0 has problem I described above, i.e. it doesn't show ``onflict during synchronization"``, but it overrides updates from other POSes

AFAK, the diffrent between in 9.0 and 10.0 on those commits below. I.e. commits are at 10.0, but not at 9.0 (we plan to backport them to 9.0) 
https://github.com/it-projects-llc/pos-addons/commit/937af52ca661edb088a0ae4764e4f0bfce1d9ba8
https://github.com/it-projects-llc/pos-addons/commit/5a2c2cb93a03b9e348f63a7f53206b00e2e55056

**Comment by timboven** [comment]
In those commits I do not directly see something that could cause this - but I also forgot to mention that we didn't use the latest 9.0 but that one that we used previous time (so could be that it is missing some additional commits as well).

But to go back to the scenario - I understand that you would say that it is almost impossible, and I would agree if it is for one table - but my scenario is for different tables (so the sessions each have another table where they are ordering this product).
And as you mention that the updates are per order (or roughly translated per table-tab?),
I do not understand how we then could have this issue - as each session is updating another order?
