### ISSUE TITLE
[10.0 - POS Debt Notebook]: Administrator user_id being set on orders

### ISSUE THREAD

**Issue by gustavovalverde** [itpp-labs/pos-addons#354]
When using POS Debt Notebook all orders are being sent to the backend with the administrator **user_id**
After uninstalling it goes back to normal. 
![image](https://user-images.githubusercontent.com/16890942/29419945-910b37fe-833e-11e7-9c02-8014960d9757.png)

**Comment by yelizariev** [comment]
Confirmed

**Comment by yelizariev** [comment]
Fixed here: https://github.com/it-projects-llc/pos-addons/pull/362

**Comment by gustavovalverde** [comment]
How could I revert the ones that already have Administrator as the user_id?

**Comment by gustavovalverde** [comment]
Actually, it's still same on my side.

**Comment by yelizariev** [comment]
@gustavovalverde it's because when you update module, odoo doesn't change fields that are not prestented in xml. In this case I removed ``act_user_id`` and it works only on new installation. I forgot about updating in existing installation. Workaround for this is to add force removing in xml:
``            <field name="act_user_id" ref="False"/>`` see https://github.com/it-projects-llc/pos-addons/pull/362/files

or remove value manually in 4 base.action.rule records created by the module. See screenshot
![screenshot-08184-10-0-fed63c-all runbot it-projects info-2017-08-27-13-05-15](https://user-images.githubusercontent.com/186131/29748120-732e63b8-8b28-11e7-98e3-b330009a74dc.png)

**Comment by gustavovalverde** [comment]
Ok, got it. 

Is there a way the fix the ones that were previously created with Administrator?
